### ISSUE TITLE
Add padding to code reproducibility block

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#1028]
Love the new look, could just use a bit of padding around the edges

**Comment by dotslashbit** [comment]
You want more padding here?
<img width="448" alt="Screenshot 2023-12-27 at 11 35 19 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/46224156/34ecac9e-cdb8-4f6f-ae0c-161aa1cbeb0f">

**Comment by anth-volk** [comment]
@nikhilwoodruff In line with Sahil, could you clarify - do you mean more padding than already exists outside the item? Do you mean within the code block itself? And do you mean vertically, horizontally, or both?

Just to put it out there, if you mean around the outside of the item, this does match what the old component had.

**Comment by anth-volk** [comment]
@dotslashbit Okay, I see now. The issue is that the block expands much wider in the policy reform calculator output. Would you be willing to alter the styling settings to harmonize that with the household reform side?

**Comment by dotslashbit** [comment]
Is this in the mobile view? I can't see any difference
<img width="922" alt="Screenshot 2023-12-27 at 11 52 28 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/46224156/cbc23de6-8200-4d0e-bf58-50880d0c160e">

Left is the policy reform and right is the house reform

**Comment by anth-volk** [comment]
I believe it's in the desktop view. In mobile, we've tended toward using a flex-box implementation that's width-agnostic, which is why there's no difference, but I believe that the desktop version has some older components that either hard-code padding values or use static positioning. You'll notice a subtle difference between the household calculator:

<img width="1440" alt="Screen Shot 2023-12-27 at 12 35 53 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/6de353d9-113b-4b08-80a7-a96f69f7c9d6">

And the policy calculator:

<img width="1439" alt="Screen Shot 2023-12-27 at 12 36 39 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/94d4fcac-c9cf-43b5-bfce-67d89f69e166">

That said, perhaps it's best to wait for Nikhil to say what he meant here.

**Comment by dotslashbit** [comment]
Okay, I'll wait for Nikhil to comment on it, but nonetheless I'm interested to work on this

**Comment by nikhilwoodruff** [comment]
Thanks both- here I meant padding in the sense of some more black between the numbers/text and the edge of the black code block
