### ISSUE TITLE
Strange error in blog when switching between pages

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1202]
I'm unable to reproduce at the moment, but I believe I was on the home page, inspected a few things in the browser console (without making any changes), then navigated to the about page. After clicking back on the home page, the app white-screened, and I received the following error in the console:

```
TypeError: t is undefined
    ee HomeBlogPreview.jsx:382
    React 7
    w scheduler.production.min.js:13
    L scheduler.production.min.js:14
    6813 scheduler.production.min.js:14
    Webpack 12
react-dom.production.min.js:189:29
    React 9
    w scheduler.production.min.js:13
    L scheduler.production.min.js:14
    (Async: EventHandlerNonNull)
    6813 scheduler.production.min.js:14
    Webpack 12
```

I'll try to update this if I run into it again and figure out what I did specifically

**Comment by cats256** [comment]
I think I managed to replicate this issue. For some interesting reason, when you reload https://policyengine.org/us when it's in inspect mode, the page turns white. But when you're not in inspect mode, the page reloads normally. The issue comes from the fact that in the HomeBlogPreview function, it uses a function called useCountryId, which gets the country id (eg: 'us') from the URL. For some reasons, the useEffect hook won't trigger inside useCountryId function when it reloads in inspect mode, which ends up leading countryId to become null. And since countryId becomes null, only 8 posts satisfy the condition in the below screenshot, instead of 42 posts. And there are two lines of code that access the 8th index (allPosts[8]) in the allPosts array (in which the 8th index doesn't exist), leading to the problem. 
 
![image](https://github.com/PolicyEngine/policyengine-app/assets/59489624/148fce1a-39ad-4159-b9e1-0b95053aa688)
![image](https://github.com/PolicyEngine/policyengine-app/assets/59489624/4d0ac798-dd62-4570-8db9-ba6705ba308b)

**Comment by anth-volk** [comment]
Is this the same error as #1167?
