### ISSUE TITLE
Add `?embed=true` to API playground Streamlit URL

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1229]
The "API playground" at the bottom of [this page](https://policyengine.org/us/api) renders as merely an empty iframe

**Comment by abhcs** [comment]
The streamlit app keeps going to sleep due to low traffic. See [this StackOverflow post](https://stackoverflow.com/questions/74545489/streamlit-app-going-to-sleep-due-to-less-traffic).

It should be visible shortly since I have woken it up:
<img width="1114" alt="Screenshot 2024-01-19 at 8 29 49 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/1e4ca36c-b9b3-4454-9aa8-21fea8289659">

**Comment by anth-volk** [comment]
Is there any way to have the app remain "awake"? Or otherwise trigger its periodic awakening? Unfortunately I don't have access to the Streamlit myself.

**Comment by anth-volk** [comment]
That seems like a simple enough fix. I'll open an issue, and I'm happy to add it myself or leave it to you

**Comment by anth-volk** [comment]
I take that back, I have no idea why I opened an issue to merely reiterate this issue

**Comment by abhcs** [comment]
I will try to fix the URL -- iirc, I had some trouble doing this before.
