### ISSUE TITLE
CTC links are broken

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#1258]
https://policyengine.org/us/research/wyden-smith-ctc

This [policy exists](http://api.policyengine.org/us/policy/44066), but the [link in the blog post](https://policyengine.org/us/policy?focus=policyOutput.policyBreakdown&reform=44066&region=us&timePeriod=2024&baseline=2) fails

**Comment by MaxGhenis** [comment]
I think this is because we renamed one of the parameters

**Comment by anth-volk** [comment]
Checking via the console - yeah, appears "ctc_expansion" no longer exists. 

I think part of this issue emerges because back in September, we dealt with situations where households contained variables that no longer existed, but we didn't deal with policies that contain variables that no longer exist, perhaps partly because an absolute ton do - perhaps we also just skip over those in the back end? I'm not entirely sure, but when creating a household with a reform baseline, this of course then breaks.

**Comment by anth-volk** [comment]
I am curious, though, @nikhilwoodruff - were you seeing the below error message on your end when you ran into problems? Or just white screens?

<img width="1440" alt="Screen Shot 2024-01-23 at 7 43 10 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/4bc73358-a267-4207-a319-755bc2ab4855">

**Comment by MaxGhenis** [comment]
I'm getting a white screen.

Would suggest we show the impact without the nonexistent parameter and add a butterbar indicating that the reform modifies a parameter that no longer exists.

**Comment by anth-volk** [comment]
I actually was about to submit a new issue - these sort of parameters now white-screen for me, as well

**Comment by anth-volk** [comment]
I am in progress on this

**Comment by anth-volk** [comment]
Closing in light of #1950
