### ISSUE TITLE
Site down on mobile

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1286]
For at least the past 30min white screen https://policyengine.org

**Comment by abhcs** [comment]
The error is probably in `react-dom` according to this screenshot from mobile debugging:

<img width="996" alt="Screenshot 2024-01-26 at 5 55 40 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/d0bcd280-1f99-44c4-a7af-dd61a81752d5">

**Comment by abhcs** [comment]
This is the error I see on the iPad simulator provided by xcode:

![Simulator Screenshot - myIpad - 2024-01-26 at 21 56 16](https://github.com/PolicyEngine/policyengine-app/assets/31144719/e7c57ca0-cb19-4cce-83b2-9cbfbf943dea)

So, I assumed it was due to the "<p> instead of <div>" error but the error has not gone away.

**Comment by abhcs** [comment]
Reverting commit 4fa4ad953712a708d8aea1c8b3ce0e6a20515930 fixes the problem for me locally. Will open a PR soon.

**Comment by cats256** [comment]
@MaxGhenis this seems to be related to issue #1202, which i identified where the issue is coming from but haven't create a fix for
