### ISSUE TITLE
Reproduce in Python only sets reported state income tax in baseline, not reform

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1337]

**Comment by anth-volk** [comment]
To be clear on this - if someone calculates a household in the US, then selects to create a reform, then wants to reproduce that entire thing in Python, would they need the same code US state income tax settings for both the baseline and the reform added in the same way that they are in Reproduce in Python for the policy calculator?

**Comment by MaxGhenis** [comment]
We should always apply the same `reported_state_income_tax` setting between baseline and reform. This should be true only for US-wide microsimulations; for state microsimulations and household simulations it should be false.

**Comment by anth-volk** [comment]
I hate to ask this question, but how does one apply a modified baseline (not reform) to a household `Situation`-type object? I tried defining a new `TaxBenefitSystem` type, but was unable to do so that way, and there's no parameter like `baseline`. I believe this is the last bit of code I need to work on before fixing this, #1327, and #1334

**Comment by MaxGhenis** [comment]
Same as with microsimulation: you modify the baseline by passing a reform.
