### ISSUE TITLE
Some edits don't work in parameter editor

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1340]
## Steps

In [this example](https://policyengine.org/us/policy?reform=2&focus=gov.irs.credits.eitc.phase_out.max_investment_income),

- change the start and end dates to `2023-01-01` and `2028-12-31` respectively, and 
- change the value to `$11,000`.

No change is observed in the graph and the edit is not registered.

## Expected

The function should change in the given range.

## Cause

A bug in the difference calculation between baseline and reform policies.

**Comment by MaxGhenis** [comment]
Interesting, that's because the new value matches the initial value. Works fine at $10,000. So we need to check if the edit changes values for any subinterval in the interval.

<img width="905" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/7aacd88a-a086-4cbf-a004-c2d7191a51c9">
