### ISSUE TITLE
Tax rate numeric input on app rounds to nearest hundredth 

### ISSUE THREAD

**Issue by fedderw** [PolicyEngine/policyengine-app#1354]
For example, when I open up `MD>Tax>Income>Rates>Head>Bracket 5>Rate`, the chart says that the rate is `0.0525`, but the input box rounds it to `0.05`. 

Likewise, the same occurs when I enter in 0,0625, as pictured below. If you put 0,0675, it rounds up to 0,07 in the input

It doesn't seem to affect the results, but it is confusing and potentially misleading to those who don't already know what the correct rate is

![image](https://github.com/PolicyEngine/policyengine-app/assets/16396180/2f91d5e5-a972-4e0b-858e-3a468f45d725)

**Comment by MaxGhenis** [comment]
Since we have `rate_unit: /1` in [this parameter](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/states/md/tax/income/rates/head.yaml), we should also be formatting this as a percentage, which would help by offering extra decimals after the percent integer. Filed #1355 on that.
