### ISSUE TITLE
Format `rate_unit: /1` as percentages in the parameter input

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1355]
As we do for `unit: /1`. See #1354 as an example.

**Comment by abhcs** [comment]
We are always rounding to 2 digits since we changed the input element. I can fix this issue by only rounding to 2 digits when we know the type is currency.

However, I do not see the metadata here:

```js
description: null
economy: true
household: true
label: "rate"
parameter: "gov.states.md.tax.income.rates.head[2].rate"
period: null
type: "parameter"
unit: null
values: {2013-01-01: 0.04}
```

Attributes such as `threshold_unit`, `rate_unit`, and `label` are missing or don't match the back end. Perhaps attributes are lost in translation to each household member?

**Comment by abhcs** [comment]
So, some attributes (`threshold_unit`, `rate_unit`) are lost in the parameter translation [here](https://github.com/PolicyEngine/policyengine-api/blob/00cb4f444657f105e061a412a786de91bc1f3b13/policyengine_api/country.py#L240). Even if the attributes were preserved they would be visible in the ancestral parameter `gov.states.md.tax.income.rates.head` and not in the parameter `gov.states.md.tax.income.rates.head[2].rate`. To fix this we have at least two options

- propagate the attributes of ancestors to descendants in the parameter translation function
- add a parent attribute to each parameter that would allow the front end to conveniently find attributes in ancestors.
