### ISSUE TITLE
Twitter feed in footer is too big

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1511]
It's several pages of scrolling. Can it have an internal scroll? If not, let's just do 1-3 tweets to keep the footer from expanding.

**Comment by anth-volk** [comment]
I actually can't even see the feed, even logged in - I still receive the "Nothing to see here" message, and I believe Nikhil does, too, so I'm pleasantly surprised to hear you can.

Since I can't tell myself, are you saying that the feed container itself extends infinitely downward? It should behave as you're describing, with an internal scroll and a fixed height.

**Comment by MaxGhenis** [comment]
https://www.loom.com/share/a0b5aecad08348f2b1e06412be0e3be5
