### ISSUE TITLE
Uncaught runtime error 

### ISSUE THREAD

**Issue by dotslashbit** [PolicyEngine/policyengine-app#1780]
I got the following error while running the web app in the localhost.

OS : MacOS 
Device: MacBook Air M2
Browser: Safari

![screenshot_2024-05-15_at_12.22.00.png](https://github.com/PolicyEngine/policyengine-app/assets/46224156/b5c14896-d14b-44c3-b8b9-13fe09f31007)

**Comment by anth-volk** [comment]
Based on a video I saw of this error, this may be driven by something causing our URL, `policyengine.org`, to redirect to `policyengine.org/undefined`, pointing to interplay with #1300 and #1471.

**Comment by anth-volk** [comment]
I believe these issues (as well as those in #1300 and #1471) are caused by the conditional within `PolicyEngine.jsx`, around line 56, as well as the country ID setting code on line 53. This code checks if a country ID is specified within the first portion of the URL after a "/". If it isn't, it pulls the browser's default language using `navigator`, then indexes into an object that maps relevant language keys to a desired country ID.

This method contains various limitations:
1. It only contains English language codes, so if the user's browser is configured in a different language, this will return a country ID of "undefined"; indeed, because of the way JavaScript objects work, unless `navigator.language` specifically returns one of the five options declared in the object (e.g., "en-NZ"), this will return "undefined" as a country ID
2. It uses the navigator method, and though I'm not incredibly familiar with it, I wouldn't be surprised if it didn't function correctly for some or all mobile users, especially those using Safari and/or mobile versions of Firefox, due to these browsers' documented tendency to be less up-to-date on modern browser APIs
3. This function does nothing to sanitize garbage country IDs. Any value placed after the TLD-terminating "/" in the URL will be treated as the country ID due to the way that the ID is pulled from the URL, which is relatively rudimentary.

I'll take a look at repairing some of these in the coming days.
