### ISSUE TITLE
Split up decile impact by total/income/substitution

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1790]
This chart is too complex IMO. Let's split them up or use radio buttons. Also income and substitution effects are the same color

<img width="894" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/ddaa8d17-a337-41db-96ae-c64af78a1cd3">

**Comment by anth-volk** [comment]
Working on this currently, but the our implementation of `DisplayImpactChart` is so tightly coupled to the logic that the radio buttons, which are a far better implementation in my opinion, are proving difficult, as it's not possible to use stateful variables within the individual impact chart components due to how they're fed into `DisplayImpactChart`. I'll see about writing some sort of wrapper component to allow this to occur.

**Comment by anth-volk** [comment]
I've looked into this some more and have found no way of actually getting the radio button logic to work here. Longer-term, I think the interface by which impact charts are displayed is coupled far too closely with one particular logic, and it should be rewritten in a way that simplifies output and allows each output pane to act as its own page.

That said, in the short term, I could break these out into three separate tabs under "overall" (or two, if you'd like the total effect line on the income and substitution effect charts, instead of giving it its own tab). Would you like me to proceed as such?

**Comment by MaxGhenis** [comment]
Out of curiosity, are the household charts with radio buttons and drop-downs written more flexibly?

**Comment by anth-volk** [comment]
Here's how the app looks with the tabbed pages.

https://github.com/PolicyEngine/policyengine-app/assets/14987227/302a2265-ac44-4c07-ab50-7446fa985737

**Comment by MaxGhenis** [comment]
Let's make them all columns

**Comment by anth-volk** [comment]
PR opened (#1821) to do so. Looking forward to hearing any critiques, desired changes, etc.
