### ISSUE TITLE
Mobile view arrows crash when navigating

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1814]
On the mobile interface (this is also the interface present at breakpoints <= 768px, so standard PCs/laptops with the screen open in half-width), pages that have new addresses in order to enable page nesting break the app. 

For example, budgetary output used to be located at `https://policyengine.org/us/policy?focus=policyOutput.budgetaryImpact...`, but now it's at `https://policyengine.org/us/policy?focus=policyOutput.budgetaryImpact.overall...`. However, the mobile output page wasn't updated to support that, so when a user uses an arrow button to navigate, the app crashes on these pages.

**Comment by MaxGhenis** [comment]
See https://www.loom.com/share/93897aa39c9c4cfc8e6646e50cebf333

**Comment by rachel-lawrie** [comment]
Adding a bit of additional detail to this issue: 

The root of the problem is that focus in https://github.com/PolicyEngine/policyengine-app/blob/master/src/layout/MobileCalculatorPage.jsx#253-269 is populated by the tree here: https://github.com/PolicyEngine/policyengine-app/blob/master/src/pages/policy/output/tree.js. It used to be a single layer tree, but it is now a nested tree. The current code in MobileCalculatorPage does not accommodate the nesting. This leads to values being searched for in https://github.com/PolicyEngine/policyengine-app/blob/master/src/pages/policy/output/ImpactTypes.jsx which do not exist and an error is thrown as a result and the app crashes.

**Comment by rachel-lawrie** [comment]
@anth-volk Can you please review this PR to ensure I am on the right track before I continue on this path? (Definitely not yet ready to merge). https://github.com/PolicyEngine/policyengine-app/pull/1947

**Comment by anth-volk** [comment]
@rachel-lawrie Sure, can do first thing tomorrow
