### ISSUE TITLE
App white screens when opening the Microsim 

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-app#1983]
Started experiencing the issue about a week ago but seems to appear consistently:

https://github.com/user-attachments/assets/241e6c2e-5748-4a29-8f56-53b211673f8d

It is solved by refreshing but sometimes it takes more than one attempt, see above

**Comment by bharateshwq** [comment]
Couldn't reproduce this in 
chrome or firefox
OS - Linux arch 
may i know get some additional details to reproduce this

**Comment by MaxGhenis** [comment]
I've also been getting it regularly on chrome mac

**Comment by anth-volk** [comment]
Unfortunately, this seems to be sporadic and inconsistent. E.g., I've also never gotten it on Firefox or Chrome on Mac

**Comment by anth-volk** [comment]
Looks like this white screening happens because of the code at:

https://github.com/PolicyEngine/policyengine-app/blob/5a48767d7ec1e85406e2f1786ef642dec75d093d/src/pages/policy/PolicyRightSidebar.jsx#L782

It looks like there are cases where, for some reason only on Chrome, the policy is somehow null at the point at which it is accessed, crashing `PolicyRightSidebar`, thereby crashing the entire policy calculator. It's unclear why the policy would be null, considering how the code is written, or why it would only occur in Chrome.
