### ISSUE TITLE
Parameter table mode

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#2067]
I think this could save a lot of time for people programming reform details of complex reforms. Instead of showing the date picker and the chart, we could show an editable table for 2024-2034 (inclusive) in both the UK and US, along with a save button. We could make this non-default, with the old layout shown until the user clicks a switch.

I'd strongly push for this even as an initially experimental feature hidden behind a URL parameter.

cc @MaxGhenis @anth-volk

**Comment by MaxGhenis** [comment]
Sounds good, especially starting with `breakdown` parameters. Can we make it 2024 onward instead of stopping at 2034?

**Comment by anth-volk** [comment]
It sounds like you're both driving toward two different things, Nikhil's being a yearly table for any given parameter so that it's easy to modify policies with annual changes over a 10-year budget window, and Max's being a table of, say, IRS brackets all being modified into perpetuity to allow for easy modeling of policies that change multiple bracket values at once.

I think these both might be doable, and either (but especially the second) would improve the interface. I think this needs a mock-up before proceeding, but is doable.

**Comment by nikhilwoodruff** [comment]
Ahh yes thanks Anthony

**Comment by MaxGhenis** [comment]
Oh I see, so still one parameter at a time but the ability to enter each year's value in separate boxes? Yes support.

**Comment by anth-volk** [comment]
I'm going to treat #39 (can't believe it's so low-numbered) as the issue surrounding scale parameters, while this one I'll treat as creating a 10-year input method
