### ISSUE TITLE
Create policy reform overview page

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#35]
With the four big numbers from the current

**Comment by anth-volk** [comment]
What is the status of this? I know it's quite an old issue

**Comment by MaxGhenis** [comment]
we still need it. currently clicking `Calculate economic impacts` directs to this wholly unsatisfying screen. it should kick off the simulation immediately and show the user a top-level summary of the impact. probably most important single UI change we can make to the microsim piece.

<img width="661" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/eca5526f-08e2-497f-8a5e-85ce84d43c59">

**Comment by anth-volk** [comment]
Would this be akin to the household summary page, then? Or are you envisioning something more distinctive?

**Comment by MaxGhenis** [comment]
[Here's what we had in v1](https://policyengine.org/us/research/the-new-policyengine-us-population-impact-page):
![image](https://github.com/PolicyEngine/policyengine-app/assets/6076111/a02abc2f-9add-43d8-9686-0b118f299db0)

We could also replace the current set of text tiles with single numbers or the charts, clickable to expand into the full page we show today.

**Comment by anth-volk** [comment]
Okay. Let me mock something up early next week. This would not only be an improvement for the app more generally, but for mobile in particular, where it's even less clear what to do next.

**Comment by anth-volk** [comment]
As a starting point, I think it'd be beneficial to mirror the household calculator's current page. I've mocked up a potential option, based heavily on the current calculator page, and would be curious to hear your thoughts. Some possible changes to this:

* We could place the reform's name where it currently says "Your reform"
* Could/should we include other items within this list?
* I'm not sure there's any benefit to placing the chart on this page, partly to allow faster loading and partly because we already have charts on the pages themselves. However, we could include a breakdown of who's better/worse off?

As a note, I do envision the font weight of the numbers being bolder, but this was a rough workup.

<img width="723" alt="Screen Shot 2023-12-27 at 2 49 17 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/a0d24b87-843b-4799-80e2-b16e2e87eee6">

**Comment by MaxGhenis** [comment]
Love this!!

**Comment by nikhilwoodruff** [comment]
Love it

**Comment by anth-volk** [comment]
Perfect! I’ll get to work on this with an aim to finish by end-of-week at earliest, mid-next week latest.
