### ISSUE TITLE
Cannot read properties of null (reading 'endsWith')

### ISSUE THREAD

**Issue by yellohCrayon** [PolicyEngine/policyengine-app#607]
Cannot read properties of null (reading 'endsWith')

<img width="1004" alt="Screenshot 2023-07-08 at 6 25 26 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/110482616/b1a9fc23-042e-4f82-81f4-12c304d805f1">

Reproduction:
navigate "Compute my household income, taxes and benefits" > "Geography" > "state_fips"

**Comment by QianruZhang78** [comment]
I'll take a look on this, as well as #608 .

**Comment by anth-volk** [comment]
I was looking into this, and it appears the culprit is [geography.py](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/input/geography.py) in the PolicyEngine US package, which does not define a `label` parameter after line 147. Seems like this would be a simple fix of opening an issue in the US package and adding that line. I'll comment the same on #608.

**Comment by nikhilwoodruff** [comment]
OK so we just need to add a catch setting the label to the name to fix this
