### ISSUE TITLE
Missing menu info

### ISSUE THREAD

**Issue by yellohCrayon** [PolicyEngine/policyengine-app#608]
Compute my household income, taxes and benefits > Geography

<img width="1109" alt="Screenshot 2023-07-08 at 6 30 32 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/110482616/ffe2c2cb-7eeb-4fb3-9eb6-896588bd9ba5">

**Comment by yellohCrayon** [comment]
Relates to https://github.com/PolicyEngine/policyengine-app/issues/607

**Comment by anth-volk** [comment]
I was looking into this, and it appears the culprit is [geography.py](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/input/geography.py) in the PolicyEngine US package, which does not define a `label` parameter after line 155. Seems like this would be a simple fix of opening an issue in the US package and adding that line. I'll comment the same on #607.
