### ISSUE TITLE
Crashes when computing non-cliff impact after computing cliff impact

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#690]
1. Create reform
2. Click `Cliff impact`
3. Once complete, click any other output, e.g. `Budgetary impact`

This produces an endless spinner. I reproduced for several reforms in both the US and UK. Going the other direction works fine.

**Comment by nikhilwoodruff** [comment]
Reproduced today

**Comment by abhcs** [comment]
It would be helpful to have an example. I have seen this problem before but have not been able to reproduce it on the master branch (right before cliff impact was hidden).

**Comment by MaxGhenis** [comment]
Huh I couldn't reproduce it just now, maybe it got fixed? https://www.loom.com/share/986eb17086da49d19fa40abba4444f6a

**Comment by abhcs** [comment]
It's possible that I fixed it in the refactor in #1019. That's why I was checking. I can also improve the design further so that you only see the "Simulating the impact..." screen once for cliff and the other types, i.e., once the impact has been fetched, it would not need re-fetching.

However, the bug may still be there only on certain configurations -- then, I would guess its a backend issue.

**Comment by MaxGhenis** [comment]
OK I'll close and reopen if we can reproduce it in the future.
