### ISSUE TITLE
Removing variable test fails

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#836]
... but the PR that it first occurred on #826 definitively did not cause it. Any ideas @anth-volk?

**Comment by anth-volk** [comment]
Would you happen to have any of the error log on this? Especially if it's a particular variable

**Comment by anth-volk** [comment]
Looks like the problem with this is that the household contains a truthy value for a tax calculation variable that was subsequently deleted, meaning that if we tried accessing this household now, the web app would prompt the user to create a new household. I'll have to think through how to re-engineer this.

**Comment by anth-volk** [comment]
It looks like [this commit](https://github.com/PolicyEngine/policyengine-us/commit/2462868161700a6744fe543c4e005af17df6a0b8) to policyengine-us removed the `fips` variable, which all US households possessed and had a default value of 6, which is truthy. This will likely mean that all past households are invalidated, but I believe the interstitial prompting a user to create a new household currently doesn't work due to the useNavigate bug I lodged elsewhere. Moving forward, to fix the test, I'll have to think of a way to make the test a bit more resilient to tax variable changes.

**Comment by anth-volk** [comment]
Fixed with #867. Closing.
